name: gradle-ci

#on : 워크플로우가 실행 될 수 있는 이벤트를 등록한다.
on:
  push:
    branches:["manin"]
    #pull_request:
      #branches: ["main"]

  jobs:
    test:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout
      uses: actions/checkout@v4
      
      -name: Set up JDK 17
      uses: actions/setup-java@4
      with
        java-version: '17'
        disttribution: 'temurin'
        cache: 'gradle'

       -name: Build with Gradle
       uses: gradle/gradle-build-action@v2
       with:
         arguments: build -x test

       -name: Setup MySQL
       uses: samin/mysql-action@v1
       with:
         mysql database: 'ohgiraffers_db'
         mysql user: ${{ secrets.MYSQL_USERNAME }}
         mysql password: ${{ secrets.MYSQL_PASSWORD }}

        -name: Test
          run: ./gradlew test
        
